name: theloungeirc
version: '0.1' 
summary: theLounge IRC Web Client
description: |
  TheLounge IRC

grade: stable
confinement: strict

apps:
  thelounge:
    environment:
      LOUNGE_HOME: $SNAP_COMMON/etc/thelounge
      LC_ALL: C
    daemon: simple
    plugs: [network-bind]
    command: wrappers/thelounge.sh
  thelounge-cli:
    environment:
      LOUNGE_HOME: $SNAP_COMMON/etc/thelounge
      LC_ALL: C
    plugs: [network-bind]
    command: wrappers/thelounge-cli.sh

parts:
  thelounge:
    plugin: nodejs
    node-engine: 4.7.1
    node-packages:
      - thelounge
  wrappers:
    plugin: dump
    source: snap/wrap/

  templates:
    plugin: dump
    source: snap/templates/
