name: theloungeirc
version: '0.2' 
summary: theLounge IRC Web Client
description: |
  TheLounge IRC

grade: stable
confinement: strict

base: core18

apps:
  thelounge:
    environment:
      THELOUNGE_HOME: $SNAP_COMMON/etc/thelounge
      LC_ALL: C
    daemon: simple
    plugs: [network-bind]
    command: wrappers/thelounge.sh
  thelounge-cli:
    environment:
      THELOUNGE_HOME: $SNAP_COMMON/etc/thelounge
      LC_ALL: C
    plugs: [network-bind]
    command: wrappers/thelounge-cli.sh

parts:
  thelounge:
    source: .
    plugin: nodejs
    nodejs-version: 12.11.1
    prime:
      - -snapcraft.yaml
      - -LICENSE
      - -README.md
      - -local
      - -package.json
  wrappers:
    plugin: dump
    source: local/wrap/
  templates:
    plugin: dump
    source: local/templates/
